# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  provision-dns:

    env:
      GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
      GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}

    defaults:
      run:
        working-directory: infra # start in the infrastructure directory, rather than root

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: fregante/setup-git-user@v1 # sets the user.name and user.email gitconfig

    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - run: |
        bash <(curl -s https://raw.githubusercontent.com/n3integration/terraform-godaddy/master/install.sh)
        cat > ~/.terraformrc <<EOF
          providers {
            godaddy = "$HOME/.terraform/plugins/terraform-godaddy"
        }
        EOF
        ls -la

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color

  build:

    needs: [provision-dns]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run export
    - run: npm run deploy
